task: detection

num_classes: 45
#remap_mscoco_category: True
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /opt/datasets/tt100k_coco/images/train/
    ann_file: /opt/datasets/tt100k_coco/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 2
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /opt/datasets/tt100k_coco/images/val/
    ann_file: /opt/datasets/tt100k_coco/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False